---
title: "Bacterial Abundance Analysis"
author: "Melvin Lin"
date: "10/28/2020"
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
```

# Import Data


```{r}
excel_sheets("~/GITHUB/144l_students/Input_Data/week3/144L_2018_BactAbund.xlsx")

metadatas <- read_excel("~/GITHUB/144l_students/Input_Data/week3/144L_2018_BactAbund.xlsx", sheet = "Metadata")
glimpse(metadatas)
unique(metadatas$Experiment) # 1 experiment
unique(metadatas$Location) # 1 location
unique(metadatas$Bottle) #8 bottles
unique(metadatas$Treatment) #4 treatments

data1 <- read_excel("~/GITHUB/144l_students/Input_Data/week3/144L_2018_BactAbund.xlsx", sheet = "Data")
glimpse(data1)

joined1 <- left_join(metadatas, data1)
names(joined1)
# summary(joined1)
glimpse(joined1)
```

# Prepare data set

```{r warning=FALSE}
cells1 <- joined1 %>% 
  mutate(Datetime = ymd_hm(Datetime),
         cells = Cells_ml * 1000) %>% 
  group_by(Treatment, Bottle) %>% 
  mutate(interv = interval(first(Datetime), Datetime),
         hours = interv/3600,
         days = hours/24) %>% 
  ungroup() %>% 
  select(Experiment:DNA_Sample, hours, days, cells) %>% 
  drop_na(cells)
  

glimpse(cells1)
```

#Plot growth curves

```{r fig.height=4, fig.width=6}
custom.colors <- c("Control" = "#377EB8", "Ash Leachate" = "#4DAF4A", "Mud Leachate" = "#E41A1C", "Glucose_Nitrate_Phosphate" = "#FF7F00")
levels <- c("Control", "Ash Leachate", "Mud Leachate", "Glucose_Nitrate_Phosphate")

cells1 %>% 
  mutate(dna = ifelse(DNA_Sample == T, "*", NA)) %>% 
  ggplot(aes(x = days, y = cells, group = interaction(Treatment, Bottle))) +
  geom_line(aes(color = factor(Treatment, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(Treatment, levels = levels)), size = 3, color = "black", shape = 21) +
  geom_text(aes(label = dna), size = 12, color = "#377EB8") +
  labs(x = "Days", y = expression(paste("Cells, L"^-1)), fill = "") +
  guides(color = F) +
  scale_color_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  facet_grid(rows = "Location")


```

# Identify exponential phase of growth

```{r}
ln_cells <- cells1 %>% 
  group_by(Treatment, Bottle) %>% 
  mutate(ln_cells = log(cells),
         diff_ln_cells = ln_cells - lag(ln_cells, default = first(ln_cells))) %>% 
  ungroup()
```

```{r fig.height=4, fig.width=15}
ln_cells %>% 
  mutate(dna = ifelse(DNA_Sample == T, "*", NA)) %>% 
  ggplot(aes(x = days, y = diff_ln_cells, group = interaction(Treatment, Bottle))) +
  geom_line(aes(color = factor(Treatment, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(Treatment, levels = levels)), size = 3, color = "black", shape = 21) +
  geom_text(aes(label = dna), size = 12, color = "#377EB8") +
  labs(x = "Days", y = expression(paste("Δln Cells, L"^-1)), fill = "") +
  guides(color = F) +
  scale_color_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  facet_grid(Location~Bottle, scales = "free") +
  theme_bw()
```

Where exponential growth occurs for each bottle:
- Bottle A ~0 - 1.2 d (T1 - T3)
- Bottle B ~0 - 0.6 d (T1 - T2)
- Bottle C ~0 - 0.6 d (T1 - T2)
- Bottle D ~0 - 0.6 d (T1 - T2)
- Bottle E ~0 - 0.6 d (T1 - T2)
- Bottle F ~0 - 0.6 d (T1 - T2)
- Bottle G ~0 - 0.6 d (T1 - T3)
- Bottle H ~0 - 0.6 d (T1 - T3)

```{r}
growth1 <- ln_cells %>% 
  mutate(exp_start = ifelse(Bottle == "A", 1, NA),
         exp_start = ifelse(Bottle == "B", 1, exp_start),
         exp_start = ifelse(Bottle == "C", 1, exp_start),
         exp_start = ifelse(Bottle == "D", 1, exp_start),
         exp_start = ifelse(Bottle == "E", 1, exp_start),
         exp_start = ifelse(Bottle == "F", 1, exp_start),
         exp_start = ifelse(Bottle == "G", 1, exp_start),
         exp_start = ifelse(Bottle == "H", 1, exp_start),
         exp_end = ifelse(Bottle == "A", 3, NA),
         exp_end = ifelse(Bottle == "B", 2, exp_end),
         exp_end = ifelse(Bottle == "C", 2, exp_end),
         exp_end = ifelse(Bottle == "D", 2, exp_end),
         exp_end = ifelse(Bottle == "E", 2, exp_end),
         exp_end = ifelse(Bottle == "F", 2, exp_end),
         exp_end = ifelse(Bottle == "G", 3, exp_end),
         exp_end = ifelse(Bottle == "H", 3, exp_end)) %>% 
  group_by(Treatment, Bottle) %>% 
  mutate(ln_cells_exp_start = ifelse(Timepoint == exp_start, ln_cells, NA),
         ln_cells_exp_end = ifelse(Timepoint == exp_end, ln_cells, NA),
         cells_exp_start = ifelse(Timepoint == exp_start, cells, NA),
         cells_exp_end = ifelse(Timepoint == exp_end, cells, NA),
         days_exp_start = ifelse(Timepoint == exp_start, days, NA),
         days_exp_end = ifelse(Timepoint == exp_end, days, NA)) %>% 
  fill(ln_cells_exp_start:days_exp_end, .direction = "updown") %>% 
 mutate(mew = (ln_cells_exp_end - ln_cells_exp_start)/(days_exp_end - days_exp_start),
         doubling = log(2)/mew,
         delta_cells = cells_exp_end - first(cells)) %>%
  ungroup()
  
check2 <- growth1 %>% 
select(Treatment, Bottle, Timepoint, exp_start, exp_end, ln_cells,  mew:delta_cells)

check <- growth1 %>% 
  select(Treatment, Bottle, Timepoint, exp_start, exp_end, ln_cells, ln_cells_exp_start:days_exp_end)

glimpse(growth1)
```

```{r}
bactcarbon1 <- growth1 %>% 
  mutate(bc = cells * (2.5 * 10^-9),
         delta_bc = delta_cells * (2.5 * 10^-9))

glimpse(bactcarbon1)
```

# Treatment averages

```{r}
averages1 <- bactcarbon1 %>% 
  group_by(Treatment, Timepoint) %>% 
  mutate(ave_bc = mean(bc),
         sd_bc = sd(bc)) %>% 
  ungroup() %>% 
  group_by(Treatment) %>% 
  mutate(ave_mew = mean(mew),
         sd_mew = sd(mew),
         ave_doubling = mean(doubling),
         sd_doubling = sd(doubling),
         ave_delta_cells = mean(delta_cells),
         sd_delta_cells = sd(delta_cells),
         ave_delta_bc = mean(delta_bc),
         sd_delta_bc = sd(delta_bc),
         ave_lag = mean(days_exp_start),
         sd_lag = sd(days_exp_start)) %>% 
  ungroup()
glimpse(averages1)
```

```{r}
averages1 %>% 
  ggplot(aes(x = days, y = ave_bc), group = interaction(Treatment, Bottle)) +
  geom_errorbar(aes(ymin = ave_bc - sd_bc, ymax = ave_bc + sd_bc, color = factor(Treatment, levels = levels)), width = 0.1) +
  geom_line(aes(color = factor(Treatment, levels = levels)), size =1) +
  geom_point(aes(fill = factor(Treatment, levels = levels)), color = "black", shape = 21, size =3) +
    facet_grid(rows = "Bottle", scales = "free") +
  labs(x = "Days", y = expression("Bacterial Carbon, µmol C L"^-1), fill = "", color = "") +
  guides(color = F) +
  theme_bw()
# This shows the change in bacterial carbon in each bottle. 

```


```{r}
bar.data1 <- averages1 %>% 
  select(Bottle, Treatment, ave_mew:sd_lag) %>% 
  distinct()
```
Mew
```{r}
bar.data1 %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_mew), group = interaction(Bottle, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_mew - sd_mew, ymax = ave_mew + sd_mew), width = 0.1) +
  facet_grid(~factor(Bottle, levels = levels), scales = "free") +
  labs(x = "", y = expression ("µ, d"^-1)) +
  theme_bw()
```

Doubling
```{r}
bar.data1 %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_doubling), group = interaction(Bottle, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_doubling - sd_doubling, ymax = ave_doubling + sd_doubling), width = 0.1) +
  facet_grid(~factor(Bottle, levels = levels), scales = "free") +
  labs(x = "", y = expression ("Doubling Time, d")) +
  theme_bw()
```

delta_bc
```{r}
bar.data1 %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_delta_bc), group = interaction(Bottle, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_delta_bc - sd_delta_bc, ymax = ave_delta_bc + sd_delta_bc), width = 0.1) +
  facet_grid(~factor(Bottle, levels = levels), scales = "free") +
  labs(x = "", y = expression ("Δ Bacterial Carbon, µmol C L"^-1)) +
  theme_bw()
```
# Save Data

```{r}
saveRDS(averages1, "~/GITHUB/144l_students/Output_Data/week3/BactAbundanceAnalysis.rds")

write_csv(averages1, "~/GITHUB/144l_students/Output_Data/week3/BactAbundanceAnalysis.csv")

```