---
title: "TOC/DOC Analysis"
author: "Melvin Lin"
date: "11/5/2020"
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
```

# Import Data


```{r}
excel_sheets("~/GITHUB/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx")

metadata1 <- read_excel("~/GITHUB/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Metadata")

data1 <- read_excel("~/GITHUB/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Data")

```

```{r}
glimpse(metadata1)
glimpse(data1)
```

# Prepare data

```{r warning=FALSE}
joined1 <- left_join(metadata1, data1)

toc1 <- joined1 %>% 
  mutate(Datetime = ymd_hm(Datetime)) %>% 
  group_by(Experiment, Bottle) %>% 
  mutate(interv = interval(first(Datetime), Datetime),
         hours = interv/3600,
         days = hours/24) %>% 
  ungroup() %>% 
  rename(sd_TOC = TOC_sd,
         sd_PTOC = PTOC_sd) %>% 
  select(Experiment:Datetime, hours, days, everything(), -c(contains("Sample"), interv))

```

```{r}
glimpse(toc1)
```

## Pivot data

```{r}
pivot_toc1 <- toc1 %>% 
  select(Experiment, Location, Bottle, Treatment, days, TOC, PTOC) %>% 
  pivot_longer(TOC:PTOC, names_to = "sample", values_to = "value")

pivot_toc_sd1 <- toc1 %>% 
  select(Experiment, Location, Bottle, Treatment, days, sd_TOC, sd_PTOC) %>% 
  pivot_longer(sd_TOC:sd_PTOC, names_to = "sample", names_prefix = "sd_", values_to = "sd")

pivoted1 <- left_join(pivot_toc1, pivot_toc_sd1) %>% 
  mutate(sample = ifelse(sample == "TOC", "Bottle", "Vial"))

glimpse(pivoted1)
```

#Plot

```{r fig.height=7, fig.width=8}
custom.colors <- c("Control" = "#377EB8", "Ash Leachate" = "#4DAF4A", "Mud Leachate" = "#E41A1C", "Glucose_Nitrate_Phosphate" = "#FF7F00", "Vial" = "#377EB8", "Bottle" = "#E41A1C")
levels <- c("Control", "Ash Leachate", "Mud Leachate", "Glucose_Nitrate_Phosphate", "Bottle", "Vial")

pivoted1 %>% 
  drop_na(value) %>% 
  mutate(Treatment = factor(Treatment, levels = levels),
         sample = factor(sample, levels = levels)) %>% 
  ggplot(aes(x = days, y = value, group = interaction(Treatment, Bottle))) +
  geom_errorbar(aes(ymin = value - sd, ymax = value + sd, color = sample), width = 0.4) +
  geom_point(aes(fill = sample), size = 3, shape = 21, alpha = 0.7) +
  scale_color_manual(values = custom.colors) +
  # scale_fit_manual(values = custom.colors) +
  labs(x = "Days", y = expression("Total Organic Carbon, µmol C L"^-1), color = "", fill = "") +
  theme_bw() + 
  facet_grid(rows = "Treatment", scales = "free") +
  guides(color = F)
```

#TOC v PTOC (bottle v vial samples)
```{r}
#install.packages("lmodel2")
library(lmodel2)

reg.data <- toc1 %>% 
  drop_na(TOC) %>% 
  filter(Timepoint > 0)

reg1 <- lmodel2(PTOC ~ TOC, data = reg.data, nperm = 99)
```

```{r}
reg1
```

```{r}
intercept <- reg1$regression.results[3, 2]
slope <- reg1$regression.results[3, 3]


two_int <- reg1$confidence.intervals[3, 2]
two_slope <- reg1$confidence.intervals[3, 4]
nine_int <- reg1$confidence.intervals[3, 3]
nine_slope <- reg1$confidence.intervals[3, 5]
```

```{r fig.height=10, fig.width=15}
reg.data %>% 
  ggplot(aes(x = TOC, y = PTOC)) +
  geom_errorbar(aes(ymin = PTOC - sd_PTOC, ymax = PTOC + sd_PTOC), width = 0.05) +
  geom_point(fill = "white", shape = 21, size = 4, alpha = 0.7) +
  geom_abline(intercept = intercept, slope = slope, color = "black", linetype = 2, size = 1) +
  geom_abline(intercept = two_int, slope = two_slope, color = "black", linetype = 3, size = 1) +
  geom_abline(intercept = nine_int, slope = nine_slope, color = "black", linetype = 3, size = 1) +
  labs(x = expression("Bottle TOC, µmol C L"^-1), y = expression("Vial TOC, µmol C L"^-1)) +
  theme_bw() +
  annotate(geom = "text", label = expression(atop("y = 1.03x - 2.12", paste("r"^2, " = 0.92, ", italic("p "), "= 3.62 * 10^-9"))), x = 75, y = 74, size = 3)
```

```{r}
bc1 <- read_rds("~/GITHUB/144l_students/Output_Data/week3/BactAbundanceAnalysis.rds")

merge <- left_join(toc1, bc1) %>% 
  select(Experiment:days, TOC:sd_PTOC, cells:diff_ln_cells, bc, ave_bc, sd_bc, everything(), -c(contains("Sample")) ) %>% 
  group_by(Experiment, Treatment, Bottle) %>% 
  fill(exp_start:sd_lag) %>% 
  ungroup()

glimpse(merge)

subset <- merge %>% 
  select(Experiment, Treatment, Bottle, days, PTOC, bc)
```

#Interpolate

```{r}
# install.packages("zoo")
library(zoo)
```

## Split

```{r}
to_interpolate1 <- merge %>% 
  select(Experiment, Bottle, Timepoint, days, PTOC, bc) %>% 
  group_by(Experiment, Bottle) #first define the grouping of dataframe

list <- to_interpolate1 %>% 
  group_split() #then convert dataframe into a list, broken up by groups (list elements)

keys <- to_interpolate1 %>% 
  group_keys() %>% 
  mutate(key = paste(Experiment, Bottle))

names(list) <- keys$key
```

## Write the function

```{r}
interp.func <- function(x) { 
  y <- zoo(x, order.by = x$days) # order observations
  interp_toc <- round(as.numeric(na.approx(y$PTOC, na.rm = F)), 1) #interpolates toc
  interp_bc <- round(as.numeric(na.approx(y$bc, na.rm = F)), 1)
  z <- cbind(y, interp_toc, interp_bc) #combines the columns
  as_tibble(z) #convert to dataframe
}
```


## Apply and Combine

```{r}
interpolated <- lapply(list, interp.func) %>% 
  plyr::ldply(., as.data.frame) %>% 
  select(-c(.id, PTOC, bc, days)) %>% 
  mutate_at(vars(Timepoint:interp_bc), as.numeric) %>% 
  left_join(merge, .)

glimpse(interpolated)
```

# Estimate DOC, Bioavailability, BGEs 

```{r}
doc <- interpolated %>% 
  mutate(doc = interp_toc - interp_bc) %>% 
  group_by(Experiment, Bottle) %>% 
  mutate(bioav_doc = (first(doc) - last(na.omit(doc))) / first(doc),
         doc_exp_end = ifelse(Timepoint == exp_end, doc, NA),
         delta_doc = first(doc) - doc_exp_end,
         tdelta_doc = first(doc) - last(na.omit(doc)),
         bge = ifelse(delta_doc > 1.5, delta_bc/delta_doc, NA)) %>% 
  fill(doc_exp_end:bge, .direction = "downup") %>% 
  ungroup()


glimpse(doc)
```

# Treatment averages
```{r}
averages <- doc %>% 
  group_by(Experiment, Treatment, Timepoint) %>% 
  mutate(ave_toc = mean(PTOC),
         sd_toc = sd(PTOC)) %>% 
  ungroup() %>% 
  group_by(Experiment, Treatment) %>% 
  mutate(ave_bioav_doc = mean(bioav_doc),
         sd_bioav_doc = sd(bioav_doc),
         ave_delta_doc = mean(delta_doc),
         sd_delta_doc = sd(delta_doc),
         ave_tdelta_doc = mean(tdelta_doc),
         sd_tdelta_doc = sd(tdelta_doc),
         ave_bge = mean(bge),
         sd_bge = sd(bge)) %>% 
  ungroup()
```

#Plot treatment curves (TOC)

```{r}
averages %>% 
  mutate(Treatment = factor(Treatment, levels = levels)) %>%
  drop_na(ave_toc) %>% 
  ggplot(aes(x = days, y = ave_toc, group = interaction (Experiment, Treatment))) +
  geom_errorbar(aes(ymin = ave_toc - sd_toc, ymax = ave_toc + sd_toc, color = Treatment), width = 0.4) +
  geom_point(aes(fill = Treatment), size = 3, shape = 21, alpha = 0.7) +
  geom_line(aes(color = Treatment), size = 1, alpha = 0.7) +
  scale_color_manual(values = custom.colors) + 
  scale_fill_manual(values = custom.colors) +
  labs(x = "Days", y = expression("Total Organic Carbon, µmol C L"^-1), color = "", fill = "") +
  theme_bw() +
  facet_grid(rows = "Treatment", scales = "free") +
  guides(color = F)
```

# Plot treatment averages (bars)
```{r}
bar.data <- averages %>% 
  select(Location, Treatment, ave_bioav_doc:sd_bge) %>% 
  distinct()
```

```{r}
bioav <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_bioav_doc, group = interaction(Location, Treatment))) +
  geom_col( color = "black", fill = "white", alpha = 1) +
  geom_errorbar(aes(ymin = ave_bioav_doc - sd_bioav_doc, ymax = ave_bioav_doc + sd_bioav_doc), width = 0.1, size = 0.5) +
  labs(x = "", y = expression(paste("Bioavailable DOC Fraction")), color = "") +
  theme_bw()
  
```

```{r}
deldoc <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_delta_doc, group = interaction(Location, Treatment))) +
  geom_col( color = "black", fill = "white", alpha = 1) +
  geom_errorbar(aes(ymin = ave_delta_doc - sd_delta_doc, ymax = ave_delta_doc + sd_delta_doc), width = 0.1, size = 0.5) +
  labs(x = "", y = expression(paste("Change in DOC (to stationary), µmol C L"^-1)), color = "") +
  theme_bw() +
  guides(fill = F)
```

```{r}
total_deldoc <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_tdelta_doc, group = interaction(Location, Treatment))) +
  geom_col( color = "black", fill = "white", alpha = 1) +
  geom_errorbar(aes(ymin = ave_tdelta_doc - sd_tdelta_doc, ymax = ave_tdelta_doc + sd_tdelta_doc), width = 0.1, size = 0.5) +
  labs(x = "", y = expression(paste("Change in DOC (total), µmol C L"^-1)), color = "") +
  theme_bw() +
  guides(fill = F)
```

```{r}
bge <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_bge, group = interaction(Location, Treatment))) +
  geom_col( color = "black", fill = "white", alpha = 1) +
  geom_errorbar(aes(ymin = ave_bge - sd_bge, ymax = ave_bge + sd_bge), width = 0.1, size = 0.5) +
  labs(x = "", y = expression(paste("Bacterial Growth Efficiency")), color = "") +
  theme_bw() +
  guides(fill = F)
```

```{r}
library(patchwork)
```

```{r fig.height=20, fig.width=10, warning=FALSE}
deldoc / total_deldoc / bioav / bge + plot_annotation(title = "Campus Point Experiments", tag_levels = "a")
```

```{r}
saveRDS(averages, "~/GITHUB/144l_students/Output_Data/week4/TOCDOCProcessed.rds")
```